<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>sign up user</title>
</head>
<body>
<div class="container">
    <h1 class="text-center">sign up user</h1>
<form method="POST" action="./process.php">
<?php if(count($error)!=0){ ?>
            <div class="alert alert-danger"><?php echo $error[0] ?></div> 
            <?php } ?>
            <div class="alert alert-success">
                <?php echo $_GET['msg']; ?>
            </div>
<div class="mb-3">
    <label for="username" class="form-label">username <i class="bi bi-person-circle"></i></label>
    <input type="text" class="form-control" id="username" name="username">
</div>
<div class="mb-3">
    <label for="email" class="form-label">Email address <i class="bi bi-envelope"></i></label>
    <input type="email" class="form-control" id="email" name="email">
</div>
<div class="mb-3">
    <label for="password" class="form-label">Password <i class="bi bi-lock-fill"></i></label>
    <input type="password" class="form-control" id="password" name="password">
</div>
<div class="mb-3">
    <label for="password2" class="form-label"> confirm Password <i class="bi bi-lock-fill"></i></label>
    <input type="password" class="form-control" id="password2" name="password2">
</div>
<div class="mb-3">
    <label for="avatar" class="form-label">choose a profile picture : <i class="bi bi-camera-fill"></i></label>
    <input type="file" class="form-control" id="avatar" name="avatar">
</div>
    <button type="submit" class="btn btn-primary" name="submit">sign up</button>
</form>  
</div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>