<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="./style/style.css">
    <title>login page</title>
</head>
<body>
    <div class="container login-container">
        <h3>you dont have an account yet ! <a href="../signupuser/home.phtml">sign up now !</a></h3>
    <form class="shadow-lg p-3 mb-5 bg-light rounded" action="./process.php" method="POST">
        <h1 class="text-center">login user</h1>
        <?php if(array_key_exists('msg',$_GET)) :  ?>
            <div class="alert alert-<?= $_GET['class'];?>">
            <?= $_GET['msg']; ?>
        </div>
            <?php endif; ?>
    <div class="mb-3" action="./process.php">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="email" name="email">
    </div>
    <div class="mb-3">
    <label for="password" class="form-label">Password</label>
    <input type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary" name="submit">Submit</button>
</form>
    </div>
</body>
</html>